### ISSUE TITLE
Instagram blocking IP

### ISSUE THREAD

**Issue by elkebe** [DorsetDigital/silverstripe-simpleinstagram#6] opened 2020-09-15 10:03 UTC
After installing the latest update for this module I'm getting an InstagramAuthException
![instagram_error](https://user-images.githubusercontent.com/31311851/93197164-6be12780-f79f-11ea-8d30-12a7e3279a20.png)

**Comment by DorsetDigital** [comment] 2020-09-15 10:15
Sadly, this is an issue with the way the underlying library operates, and Instagram's restrictions.   It's a duplicate of #5 

Closing for now, updates to the module will be logged on the other ticket

**Closed as completed by DorsetDigital** 2020-09-15 10:15 UTC
Labels: duplicate
